# Generated by Django 6.0.4 on 2026-04-25 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_residentrecord'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewed_post',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apartments.apartment'),
        ),
    ]
