# Generated by Django 6.0.4 on 2026-04-21 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('price_range', models.CharField(choices=[('BUDGET', '$ - Budget Friendly'), ('MID', '$$ - Mid Range'), ('PREMIUM', '$$$ - Premium/Gourmet')], default='MID', max_length=10)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
