# Generated by Django 6.0.4 on 2026-04-21 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Green Valley Apartment, Unit 4B', max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Total rent for the apartment', max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_rooms', models.IntegerField(default=1)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('house_rules', models.TextField(blank=True, help_text='e.g. No smoking, No late night music', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_apartments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
