# Generated by Django 6.0.4 on 2026-04-21 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='security_deposit',
        ),
        migrations.AddField(
            model_name='apartment',
            name='area',
            field=models.CharField(default='', help_text='e.g. Manhattan, Gulshan, or Downtown', max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_apartments', to=settings.AUTH_USER_MODEL),
        ),
    ]
