# Generated by Django 6.0.4 on 2026-04-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_remove_apartment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='house_rules',
        ),
    ]
