# Generated by Django 6.0.4 on 2026-04-24 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_apartment_house_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='apartments.apartment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resident Record',
                'verbose_name_plural': 'Resident Records',
                'unique_together': {('resident', 'apartment', 'is_active')},
            },
        ),
    ]
