# Generated by Django 6.0.4 on 2026-05-06 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_residentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total rent for the apartment', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_rooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
