# Generated by Django 6.0.4 on 2026-04-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_liked_by_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResidentRecord',
        ),
    ]
