# Generated by Django 6.0.4 on 2026-04-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('househelp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='househelp',
            name='bio',
        ),
    ]
