# Generated by Django 6.0.4 on 2026-04-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househelp', '0003_remove_househelp_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='househelp',
            name='availability_schedule',
        ),
        migrations.RemoveField(
            model_name='househelp',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='househelp',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='househelp',
            name='review_count',
        ),
        migrations.AddField(
            model_name='househelp',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
