# Generated by Django 6.0.4 on 2026-04-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househelp', '0004_remove_househelp_availability_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='househelp',
            name='area',
            field=models.CharField(default='', help_text='e.g. Manhattan, Gulshan, or Downtown', max_length=100),
        ),
        migrations.AddField(
            model_name='househelp',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
