# Generated by Django 6.0.4 on 2026-05-06 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househelp', '0005_househelp_area_househelp_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='househelp',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='househelp',
            name='expected_salary',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
